name: Publish to npm

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

    #   - name: Run tests
    #     run: npm test
        
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Determine version bump
        id: version-bump
        run: |
          # Get latest commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Determine version bump type based on commit message
          if [[ "$COMMIT_MSG" == *"#major"* ]]; then
            echo "VERSION_TYPE=major" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MSG" == *"#minor"* ]]; then
            echo "VERSION_TYPE=minor" >> $GITHUB_OUTPUT
          else
            echo "VERSION_TYPE=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        run: |
          npm version ${{ steps.version-bump.outputs.VERSION_TYPE }} -m "Bump version to %s [skip ci]"
          
      - name: Push version bump
        run: git push --follow-tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}